import "./globals.css";
import { Inter, Poppins } from 'next/font/google';

const inter = Inter({
  weight: ['400', '500', '700'], 
  subsets: ['latin'], 
  variable: "--inter",
});

const poppins = Poppins({
  weight: ['400', '500', '600'], 
  subsets: ['latin'], 
  variable: "--poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable} antialiased`}>
      <body>
        {children}
      </body>
    </html>
  );
}
